public class Loading_
{
    public void Vt()
    {
        System.out.println("\n\n\n\n\n\n");
    }
    public void Loading()throws InterruptedException
    {
        Loading_ ob = new Loading_();
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹         ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹          ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹           ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹          ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹          ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹           ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹          ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                   ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("           ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("           ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("           ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("                  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("    ⏹ ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("            ⏹     ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                  ");
        System.out.print("                                                                      ");
        System.out.println("           ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("            ⏹     ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("                   ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("            ⏹     ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("             ⏹     ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹  ");
        System.out.print("                                                                      ");
        System.out.println("  ⏹ ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("           ⏹      ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹ ⏹ ⏹ ⏹ ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("  ⏹ ⏹ ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("         ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("          ⏹       ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("       ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("  ⏹   ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹      ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹ ⏹ ⏹  ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("⏹      ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹       ");
        System.out.print("                                                                      ");
        System.out.println("    ⏹ ⏹ ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("        ⏹ ⏹ ⏹    ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹        ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹      ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹ ⏹  ");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹ ⏹  ");
        System.out.print("                                                                      ");
        System.out.println("      ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹   ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹    ");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹  ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹     ");
        System.out.print("                                                                      ");
        System.out.println("   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹  ⏹ ⏹ ⏹ ⏹ ⏹  ⏹");
        System.out.print("                                                                      ");
        System.out.println("     ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹  ");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹    ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹  ⏹ ⏹ ⏹ ⏹ ⏹  ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹    ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹   ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹   ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
        ob.Vt();
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        System.out.print("                                                                      ");
        System.out.println("⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹ ⏹");
        Thread.sleep(100);
        System.out.println("\f");
    }
}